### ISSUE TITLE
Create show current online learners

### ISSUE THREAD

**Issue by RikaAJN** [TE-Flutter/Risehallrepo#31]
On this screen, users can be able to click and see number of learners online but not see any names. Just number of learners online.

**Comment by GwynbleiddRU** [comment]
Again, it depends on how do you store your learners.. Assuming you use firebase... :)

_In firebase **realtime databases** you can find a cool trick as "presence" which [aims to track your users online](https://firebase.google.com/docs/firestore/solutions/presence).. You can get the list and then sort them by the required course or ust list all of them, its up to you_

Still that means youre going to use realtime databases instead of a firestore (in case we're still looking for using a firebase)..
Using a **firestore** you will have to change the user record from offline to online and vice versa each time they enter/exit the app to track if its online or not.. Takes a lot of queries actually but still, that seems to be the only solution without other instruments. 

Then you just search for a users like (assuming the field responsible for tracking the user online status is boolean and is called "isOnline"):
```
        var userSnapshots = FirebaseFirestore.instance
        .collection('learners')
        .where('isOnline', isEqualTo: true)
        .snapshots();
```
So you get a list of document snapshots of your users who're actually online.. We're almost there :)
Now just get the count of the snapshots you've found with:
`    var count = conversationsSnapshots.length;`

_i'm pretty sure it should work but in case smth goes wrong you can always do a dumb-style counting (in case length is not what it should mean here)_
```
    var count = 0;
    conversationsSnapshots.forEach((element) {
      count++;
    });
```
